name = "daily-index-tracker-admin"
compatibility_date = "2024-08-20"

[env.production]
name = "daily-index-tracker-admin"

[env.staging]
name = "daily-index-tracker-admin-staging"

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables for the frontend
[vars]
VITE_API_BASE_URL = "https://admin-console.your-domain.workers.dev"
VITE_APP_NAME = "Daily Index Tracker"
VITE_APP_VERSION = "1.0.0"

[env.production.vars]
VITE_API_BASE_URL = "https://admin-console.your-domain.workers.dev"

[env.staging.vars]
VITE_API_BASE_URL = "https://admin-console-staging.your-domain.workers.dev"