name = "admin-console-worker"
main = "index.js"
compatibility_date = "2024-08-17"

# KV Namespaces
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "ec1a3533310145cf8033cd84e1abd69c"
preview_id = "2969e90d5c9c4bc0ab14caa50f7b9756"

[[kv_namespaces]]
binding = "JOBS_KV"
id = "ba267159e4614fbb84edfc7cd902692c"
preview_id = "f8687ea189594eb886cde37edda4264f"

[[kv_namespaces]]
binding = "PACKAGES_KV"
id = "935d01fc21f0462fad041b2adfc0d17a"
preview_id = "825902cc80ad425eacf4aefc25c723dc"

[[kv_namespaces]]
binding = "TIMESERIES_KV"
id = "134812605b5b435eab23b4a72d8b7ced"
preview_id = "695488b5895646f190511fe25cf90e7b"

# Environment variables
[vars]
ENVIRONMENT = "development"
N8N_BASE_URL = "http://localhost:5678"

# Secrets (set via wrangler secret put)
# CLOUDFLARE_ACCESS_JWT_SECRET
# N8N_API_KEY
# ADMIN_API_KEY

# Routes for custom domain (optional)
# routes = [
#   { pattern = "admin.yourdomain.com/api/*", zone_name = "yourdomain.com" }
# ]

# Cron triggers (if needed for maintenance tasks)
# [[triggers]]
# cron = "0 2 * * *"  # Daily at 2 AM for cleanup tasks