name = "chart-generation-worker"
main = "index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ENVIRONMENT = "development"

# KV Namespaces
[[kv_namespaces]]
binding = "TIMESERIES_KV"
id = "134812605b5b435eab23b4a72d8b7ced"
preview_id = "695488b5895646f190511fe25cf90e7b"

[[kv_namespaces]]
binding = "CHARTS_KV"
id = "935d01fc21f0462fad041b2adfc0d17a"
preview_id = "825902cc80ad425eacf4aefc25c723dc"

# R2 Buckets
[[r2_buckets]]
binding = "CHARTS_BUCKET"
bucket_name = "chart-generation-bucket"

# Secrets (set via wrangler secret put)
# CHART_API_KEY - API key for authentication
# EXTERNAL_CHART_API_KEY - API key for external chart services

[build]
command = ""

[env.production]
name = "chart-generation-worker-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "TIMESERIES_KV"
id = "your-prod-timeseries-kv-namespace-id"

[[env.production.kv_namespaces]]
binding = "CHARTS_KV"
id = "your-prod-charts-kv-namespace-id"

[[env.production.r2_buckets]]
binding = "CHARTS_BUCKET"
bucket_name = "chart-generation-bucket-prod"